language: python
python:
    - "3.4"
    - "3.5"
services:
    - redis-server
install:
    - pip install -r requirements/development.txt
script:
    - pep8 .
    - make test
notifications:
    slack: yujuteam:eWkDBQrRPDHZp8eyEfKpbLH7
