language: python
python:
    - "3.4"
    - "3.5"
addons:
    postgresql: '9.3'
services:
    - redis-server
install:
    - pip install -r requirements/development.txt
before_script:
    - psql -c 'CREATE DATABASE english_diary;' -U postgres
    - make migrate
script:
    - pep8 .
    - python english_diary/manage.py test users diaries 
    - coverage run --source=english_diary english_diary/manage.py test users diaries
notifications:
    slack: yujuteam:eWkDBQrRPDHZp8eyEfKpbLH7
after_success: coveralls
